services:
  - type: web
    name: ecostrategy_ai_mvp
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    pythonVersion: 3.9   
    envVars:
      - key: openai_api_key
        sync: false